name: batebrisa
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  carousel_slider: ^5.0.0
  flutter:
    sdk: flutter
  flutter_map: ^7.0.2
  gap: ^3.0.1
  latlong2: ^0.9.1
  url_launcher: ^6.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets: 
  - 'assets/img/mapa.png'
  - 'assets/img/logo.png'
  - 'assets/img/enseada1.jpg'
  - 'assets/img/enseada2.webp'
  - 'assets/img/enseada3.jpg'